appname:          Markdown Edit
canonical:        https://markdownedit.com

title:            Markdown Edit
description:      The Markdown Editor for Windows
url:              https://markdownedit.com
author:           Mike Ward
logo:             /images/logo.png

owner:
  name:           Mike Ward
  avatar:         avatar.png
  bio:            Programmer, [correction Hack], Bourbon Drinker
  email:          mike@mike-ward.net
  twitter:        mikeward_aa
  github:         mike-ward
  instagram:      
  dribbble:       
  disqus:         mikeward_aa
  location:       Ann Arbor, MI  USA

twitter:
  username:       mikeward_aa

author:
  twitter:        mikeward_aa
  
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mentions
  - jemoji
