appname:          'Markdown Edit'
canonical:        http://markdownedit.com/

title:            'Markdown Edit'
description:      'A full-featured Markdown editor for Windows with an emphasis on content and keyboard shortcuts'
url:              http://markdownedit.com/
author:           'Mike Ward'
logo:             /images/logo.png

owner:
  name:           Mike Ward
  avatar:         avatar.png
  bio:            Programmer, correction Hack, Bourbon Drinker
  email:          mike@mike-ward.net
  twitter:        mikeward_aa
  github:         mike-ward
  instagram:      
  dribbble:       
  disqus:         mikeward_aa
  location:       "Ann Arbor, MI  USA"

twitter:
  username:       mikeward_aa

gems:
  - jekyll-seo-tag  